# -*- coding: utf-8 -*-
import json, pathlib
ROOT = pathlib.Path(__file__).resolve().parents[1]

Z_TOAST = {
    "connectFailed": "连接失败",
    "imageLoadFailed": "图片加载失败",
    "movedToTopLevel": "已移到顶层",
    "movedToTargetGroup": "已移动到目标分组",
    "titleAndContentRequired": "标题和内容必填",
    "packedWithPath": "已打包: {{path}}",
    "hostIpRequired": "请填写主机 IP",
    "noPasteShort": "无粘贴内容",
    "readSourceFailed": "读取源失败",
    "savedWithName": "已保存 {{name}}",
    "testingName": "正在测试 {{name}}…",
    "searchConnectOk": "✅ 连通正常",
    "searchTestFailed": "测试失败",
    "clearedConfigFor": "已清空 {{name}} 配置",
    "accountDeactivated": "账户已注销",
    "deactivateAccountFailed": "注销失败",
    "mailSettingsSaved": "发信设置已保存",
    "aiConfigSavedShort": "AI 配置已保存",
    "selectUserFirst": "请先选择用户",
    "savedToThisUser": "已保存到该用户",
    "systemConfigApplied": "已将系统配置应用到该用户",
    "revokedShort": "已撤销",
    "resetDone": "已重置",
    "resetOpFailed": "重置失败",
    "configWritten": "已写入配置",
    "unrestrictFailed": "解除失败",
    "userPaused": "已暂停",
    "userResumed": "已恢复",
    "exportedNItems": "已导出 {{n}} 条",
    "taskNameRequired": "请填写任务名",
    "taskContentRequired": "请填写任务内容",
    "taskNotFound": "任务不存在",
    "apiCodeRequired": "请填写接口 code",
    "schedulerOn": "已启用",
    "schedulerOff": "已停用",
    "queuedWithRun": "已加入执行队列，run_id={{id}}",
    "executeFailed": "执行失败",
    "batchCreated": "已创建任务 #{{id}}，共 {{total}} 台主机",
    "fillIdWithHint": "请填写{{hint}} ID",
    "feedbackRecalled": "已撤回",
    "markedNRead": "已标 {{n}} 条为已读",
    "ignoredN": "已忽略 #{{id}}",
    "reopenedN": "已恢复 #{{id}}",
    "replyRecalled": "已撤回回复",
    "repliedToN": "已回复 #{{id}}",
    "replied": "已回复",
    "shown": "显示",
    "hidden": "隐藏",
    "loginWidgetSaved": "已保存：{{label}}（{{on}}）",
    "subjAndBodyRequired": "请填写主题与正文",
    "mailSentOrPending": "邮件已发出",
    "mailNotSentRecorded": "邮件未发出，已记录到回复历史",
    "failGeneric": "失败",
    "retreatFailed": "撤回失败",
    "newApiToken": "已创建新令牌",
    "mustTypeDelete": "未输入 DELETE，已取消注销",
    "passMin6": "密码至少6个字符",
    "pwdResetOk": "密码已重置",
    "submitted": "已提交",
    "retrySubmitted": "已提交重试",
    "actionCancelled": "已取消",
    "fillReplyContent": "请填写回复内容",
    "fillReplyShort": "请填写回复",
}
Z_CONFIRM = {
    "createApiTokenTitle": "创建 API 访问令牌",
    "createApiTokenBody": "确认创建新的 API 访问令牌？\n\n注意：完整令牌仅会显示一次。",
    "createApiTokenBodyNamed": "确认创建新的 API 访问令牌？\n备注名称：{{name}}\n\n注意：完整令牌仅会显示一次。",
    "deleteAccountStep1Title": "注销账户 · 第 1 步 / 共 2 步",
    "deleteAccountStep1Body": "确认要注销自己的账户吗？\n\n此操作将【不可逆地】删除你的所有数据，包括：\n• 你创建的所有主机、凭证、分组、标签；\n• 你分享给别人的主机，将从对方账号里撤销；对方因这些主机产生的聊天会话、知识、提示词、标签、通道也将一并删除；\n• 你的所有 AI 会话与消息、API 令牌、个人发信配置、触发任务、定时任务、批量操作等；\n• 你的文件工作区 web/fs 中的全部文件。\n\n确定要继续吗？",
    "trialResetTitle": "重置共享 Key 计数",
    "trialResetBody": "确认把用户「{{user}}」的系统共享 Key 调用计数清零吗？之后该用户可继续使用共享 Key 至多 {{limit}} 次。",
    "trialUnlockTitle": "写入系统配置并解除次数限制",
    "trialUnlockBody": "确认为用户「{{user}}」写入系统默认 AI 配置吗？\n\n将把 Key / URL / Model 复制到该用户账号；\n之后该用户按自有配置调用，不再受共享 Key 配额限制。",
    "clearTableTitle": "确认清空",
    "clearOpLogsBody": "确定要清空操作日志吗？此操作不可恢复。",
    "clearAllBatchBody": "确定要清空全部批量任务记录吗？此操作不可恢复。",
    "clearSearchConfig": "确定要清空 {{name}} 的配置（包括 API Key）吗？此操作不可恢复。",
    "suspendUser": "确定暂停用户「{{name}}」？暂停后该用户无法登录，仅管理员可恢复。",
    "deleteUser": "确定删除用户「{{name}}」？将清除该用户一切数据，不可恢复。",
    "deleteCron": "确定删除该定时任务？将同时删除其全部执行历史与会话记录，不可恢复。",
    "cancelBatch": "确定取消该批量任务？",
    "recallFeedback": "确定撤回反馈 #{{id}} ？此操作不可恢复。",
    "markAllFeedbackRead": "把所有「未读」反馈标为已读？",
    "recallReplyPhysical": "撤回此回复（物理删除）？若该反馈再无回复，状态将退回 open。",
    "deleteThisReply": "删除此回复？",
    "deleteMessageThread": "删除留言 #{{id}}（含其全部回复）？此操作不可恢复。",
    "deleteRequestThread": "删除申请 #{{id}}（含全部邮件回复历史）？此操作不可恢复。",
}
E_TOAST = {
    "connectFailed": "Connection failed",
    "imageLoadFailed": "Image failed to load",
    "movedToTopLevel": "Moved to top level",
    "movedToTargetGroup": "Moved to the target group",
    "titleAndContentRequired": "Title and content are required",
    "packedWithPath": "Packed: {{path}}",
    "hostIpRequired": "Enter the host IP",
    "noPasteShort": "Nothing to paste",
    "readSourceFailed": "Failed to read source",
    "savedWithName": "Saved {{name}}",
    "testingName": "Testing {{name}}…",
    "searchConnectOk": "✅ Connection OK",
    "searchTestFailed": "Test failed",
    "clearedConfigFor": "Cleared config for {{name}}",
    "accountDeactivated": "Account closed",
    "deactivateAccountFailed": "Account closure failed",
    "mailSettingsSaved": "Mail settings saved",
    "aiConfigSavedShort": "AI settings saved",
    "selectUserFirst": "Select a user first",
    "savedToThisUser": "Saved to this user",
    "systemConfigApplied": "System config applied to this user",
    "revokedShort": "Revoked",
    "resetDone": "Reset",
    "resetOpFailed": "Reset failed",
    "configWritten": "Config written",
    "unrestrictFailed": "Operation failed",
    "userPaused": "User suspended",
    "userResumed": "User restored",
    "exportedNItems": "Exported {{n}} record(s)",
    "taskNameRequired": "Enter a task name",
    "taskContentRequired": "Enter task content",
    "taskNotFound": "Task not found",
    "apiCodeRequired": "Enter the API code",
    "schedulerOn": "Enabled",
    "schedulerOff": "Disabled",
    "queuedWithRun": "Queued (run_id={{id}})",
    "executeFailed": "Execution failed",
    "batchCreated": "Task #{{id}} created for {{total}} host(s)",
    "fillIdWithHint": "Enter the {{hint}} ID",
    "feedbackRecalled": "Recalled",
    "markedNRead": "Marked {{n}} as read",
    "ignoredN": "Ignored #{{id}}",
    "reopenedN": "Reopened #{{id}}",
    "replyRecalled": "Reply removed",
    "repliedToN": "Replied #{{id}}",
    "replied": "Replied",
    "shown": "show",
    "hidden": "hide",
    "loginWidgetSaved": "Saved: {{label}} ({{on}})",
    "subjAndBodyRequired": "Enter subject and body",
    "mailSentOrPending": "Email sent",
    "mailNotSentRecorded": "Email not sent; note saved in history",
    "failGeneric": "Failed",
    "retreatFailed": "Recall failed",
    "newApiToken": "New API token created",
    "mustTypeDelete": "Type DELETE to confirm account closure",
    "passMin6": "Password must be at least 6 characters",
    "pwdResetOk": "Password reset",
    "submitted": "Submitted",
    "retrySubmitted": "Retry submitted",
    "actionCancelled": "Cancelled",
    "fillReplyContent": "Enter reply content",
    "fillReplyShort": "Enter a reply",
}
E_CONFIRM = {
    "createApiTokenTitle": "Create API token",
    "createApiTokenBody": "Create a new API access token?\n\nThe full token is shown only once.",
    "createApiTokenBodyNamed": "Create a new API access token?\nLabel: {{name}}\n\nThe full token is shown only once.",
    "deleteAccountStep1Title": "Close account · step 1 of 2",
    "deleteAccountStep1Body": "Permanently delete your account?\n\nThis cannot be undone. It removes:\n• All hosts, credentials, groups, and tags you created\n• Hosts you shared (revoked for others; their related chats, knowledge, prompts, tags, and channels for those hosts are also removed)\n• All your AI sessions and messages, API tokens, mail settings, trigger jobs, scheduled jobs, and batch operations\n• All files in your web/fs workspace\n\nContinue?",
    "trialResetTitle": "Reset shared Key usage",
    "trialResetBody": "Reset the shared Key call count for “{{user}}”? They can use the shared Key up to {{limit}} more times afterward.",
    "trialUnlockTitle": "Apply system AI config to user",
    "trialUnlockBody": "Write the default system AI config to “{{user}}”?\n\nThis copies Key / URL / Model to their user_ai_config. They will use their own quota, not the shared Key limit.",
    "clearTableTitle": "Clear",
    "clearOpLogsBody": "Delete all operation logs? This cannot be undone.",
    "clearAllBatchBody": "Delete all batch job records? This cannot be undone.",
    "clearSearchConfig": "Clear all settings (including API Key) for {{name}}? This cannot be undone.",
    "suspendUser": "Suspend “{{name}}”? They cannot sign in until an admin restores the account.",
    "deleteUser": "Delete “{{name}}” and all of their data? This cannot be undone.",
    "deleteCron": "Delete this scheduled job and all run history and session records? This cannot be undone.",
    "cancelBatch": "Cancel this batch job?",
    "recallFeedback": "Recall feedback #{{id}}? This cannot be undone.",
    "markAllFeedbackRead": "Mark all “unread” feedback as read?",
    "recallReplyPhysical": "Delete this reply permanently? If this feedback has no replies left, its status reverts to open.",
    "deleteThisReply": "Delete this reply?",
    "deleteMessageThread": "Delete message #{{id}} and all replies? This cannot be undone.",
    "deleteRequestThread": "Delete application #{{id}} and all email history? This cannot be undone.",
}

for loc, tpatch, cpatch in [
    (ROOT / "web/locales/zh-CN/toasts.json", Z_TOAST, Z_CONFIRM),
    (ROOT / "web/locales/en/toasts.json", E_TOAST, E_CONFIRM),
]:
    o = json.loads(loc.read_text(encoding="utf-8"))
    o["toast"].update(tpatch)
    o["confirm"].update(cpatch)
    loc.write_text(json.dumps(o, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("merged", loc, "+toast", len(tpatch), "+confirm", len(cpatch))
